spring:
  application:
    name: spring-security-service

  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  # ===========================
  # H2 Console Configuration
  # ===========================
  h2:
    console:
      enabled: true
      path: /h2-console
  # ===========================
  # JPA / Hibernate Configuration
  # ===========================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  flyway:
    enabled: true # Enable Flyway migrations
    locations: classpath:flyway/migration # Location of migration scripts
    baseline-on-migrate: true

logging:
  level:
    root: info
    org.hibernate: error
    com.zaxxer.hikari: error
    org.apache: error
    org.springframework.boot.autoconfigure: error
    org.springframework.security: debug

# curl -u "admin:admin" http://localhost:8080/transaction/health